sudo: false
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
      - libdbus-1-dev libssl-dev systemd libsystemd-daemon-dev protobuf-compiler
